export const GET_ALL_FREINDS = 'GET_ALL_FREINDS';

export const ADD_FRIEND_ALLLIST = 'ADD_FRIEND_ALLLIST';
export const REMOVE_FRIEND_ALLLIST = 'REMOVE_FRIEND_ALLLIST';

export const ADD_FRIEND_ADDLIST = 'ADD_FRIEND_ADDLIST';
export const REMOVE_FRIEND_ADDLIST = 'REMOVE_FRIEND_ADDLIST';
